module.exports = {
  siteMeta: {
    brandName: 'SoloSuccess Solutions',
    founderName: 'Fran',
    baseUrl: 'https://prettyinpurple2021.github.io/SoloSuccessPortfolio',
    socialHandle: '@solosuccessai',
    contactEmail: 'founder@solosuccesss.com',
    fontshareHref: 'https://api.fontshare.com/v2/css?f[]=cabinet-grotesk@400,700,800,900&f[]=satoshi@400,500,700&f[]=jet-brains-mono@400,700&display=swap',
    rootPages: [
      'index.html',
      'founder.html',
      'blog.html',
      'admin.html',
      '404.html'
    ]
  },
  products: [
    {
      id: 'solosuccess-ai',
      shortName: 'AI',
      num: '01',
      name: 'SoloSuccess',
      nameAccent: 'AI',
      tagline: 'Your AI co-founder, always on.',
      desc: 'The intelligence layer powering the entire SoloSuccess ecosystem. Strategy generation, task automation, and real-time decision support — available 24/7, fully aligned with your goals, never needing a salary.',
      color: '#7c4dff',
      paper: '#ede7f6',
      status: 'soon',
      whoItsFor: 'Solo founders who need strategic guidance, automated backend workflows, and round-the-clock decision support.',
      icon: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 2a2 2 0 0 1 2 2c0 .74-.4 1.39-1 1.73V7h1a7 7 0 0 1 7 7h1a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1h-1v1a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-1H2a1 1 0 0 1-1-1v-3a1 1 0 0 1 1-1h1a7 7 0 0 1 7-7h1V5.73A2 2 0 0 1 10 4a2 2 0 0 1 2-2z"/><circle cx="9" cy="14" r="1" fill="currentColor"/><circle cx="15" cy="14" r="1" fill="currentColor"/></svg>`,
      features: [
        { title: 'Strategy Engine', desc: 'Generate go-to-market strategies, product roadmaps, and growth plans tailored to your specific stage and context.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M2 20h20M6 20V10l6-6 6 6v10"/></svg>` },
        { title: 'Task Automation', desc: 'Delegate recurring tasks to AI agents that execute autonomously — from email drafting to research to data processing.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/></svg>` },
        { title: 'Decision Support', desc: 'Get AI-backed analysis on key decisions: pricing, positioning, hiring, partnerships — with full reasoning shown.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M12 8v4l3 3"/></svg>` },
        { title: 'Ecosystem Sync', desc: 'SoloSuccess AI is the connective tissue between all 7 products — context flows between them so nothing starts from scratch.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="M8.59 13.51l6.83 3.98M15.41 6.51l-6.82 3.98"/></svg>` },
        { title: 'Context Memory', desc: 'Remembers your business context, preferences, and history so every interaction builds on the last.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>` },
        { title: '24/7 Availability', desc: 'No downtime, no PTO, no scheduling. Your AI co-founder is always ready when you need it.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/></svg>` },
      ],
      steps: [
        { label: 'Tell it your context', title: 'Onboard once', desc: 'Describe your business, stage, goals, and constraints. SoloSuccess AI builds a persistent model of your company that improves over time.' },
        { label: 'Ask anything', title: 'Query or delegate', desc: 'Ask strategic questions, request analysis, or delegate tasks entirely. The AI works in the background and reports back.' },
        { label: 'Review + refine', title: 'Iterate fast', desc: 'Review outputs, push back, refine the context. Every session makes the AI more useful for your specific situation.' },
        { label: 'Ship', title: 'Execute with confidence', desc: 'Move faster and with more certainty than founders who are guessing alone.' },
      ],
      pricing: null,
      waitlistTitle: 'Be first when I launch.',
      waitlistDesc: 'SoloSuccess AI is in private development. Join the waitlist to get early access and founding-member pricing.',
    },
    {
      id: 'academy',
      shortName: 'Academy',
      num: '02',
      name: 'SoloSuccess',
      nameAccent: 'Academy',
      tagline: 'Learn. Build. Ship.',
      desc: 'AI-personalized courses and playbooks built for solo founders. Every lesson is filtered through your actual business context — no generic advice, no filler, just tactics that work when you\'re building alone.',
      color: '#00cfff',
      paper: '#e3f2fd',
      status: 'live',
      whoItsFor: 'Early-stage builders looking for personalized, actionable, no-nonsense frameworks to learn and ship products.',
      icon: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M22 10v6M2 10l10-5 10 5-10 5z"/><path d="M6 12v5c3 3 9 3 12 0v-5"/></svg>`,
      features: [
        { title: 'Adaptive Curriculum', desc: 'The course path adjusts based on your business stage, industry, and goals. No wasted time on topics you\'ve already mastered.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg>` },
        { title: 'Founder Playbooks', desc: 'Condensed, battle-tested frameworks for launching, growing, and sustaining a solo-operated business.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/></svg>` },
        { title: 'Live Workshops', desc: 'Weekly sessions with practitioners who\'ve built solo — not theory professors. Real war stories, real tactics.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>` },
        { title: 'AI Study Partner', desc: 'Ask questions mid-lesson, get personalized explanations, and apply concepts directly to your own business in real time.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>` },
        { title: 'Progress Tracking', desc: 'Visual dashboards showing where you are in your learning journey, what you\'ve completed, and what\'s next.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/></svg>` },
        { title: 'Certification', desc: 'Earn a verified Solo Founder certification to display on your profile and prove your systematic approach to building.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="8" r="7"/><polyline points="8.21 13.89 7 23 12 20 17 23 15.79 13.88"/></svg>` },
      ],
      steps: [
        { label: 'Profile your business', title: 'Tell me where you are', desc: 'Answer 5 questions about your stage, goals, and gaps. Academy builds a personalised learning path in under 60 seconds.' },
        { label: 'Start your first module', title: 'Learn in sprints', desc: 'Modules are 15–20 minutes each. Consume them when you have time — even between client calls or during lunch.' },
        { label: 'Apply to your business', title: 'Build while you learn', desc: 'Every lesson ends with a direct action you can take in your business today, not someday.' },
        { label: 'Track progress', title: 'See yourself grow', desc: 'Watch your skills map fill out as you complete modules. Your certification unlocks when you\'ve hit every milestone.' },
      ],
      pricing: [
        { tier: 'Free', price: '$0', note: 'Forever free · No credit card', badge: null, featured: false, features: ['5 core modules', 'Founder playbook library', 'Community access', 'Basic AI study partner'] },
        { tier: 'Builder', price: '$29', priceSub: '/mo', note: 'Billed monthly · Cancel anytime', badge: 'Most Popular', featured: true, features: ['Full course library (50+ modules)', 'Weekly live workshops', 'Advanced AI study partner', 'Progress tracking + certification', 'Priority community access'] },
        { tier: 'Pro', price: '$79', priceSub: '/mo', note: 'Billed monthly · Cancel anytime', badge: null, featured: false, features: ['Everything in Builder', '1-on-1 mentor sessions', 'Private founder cohort', 'Early access to new modules', 'White-glove onboarding'] },
      ],
    },
    {
      id: 'content-factory',
      shortName: 'Content',
      num: '03',
      name: 'Content',
      nameAccent: 'Factory',
      tagline: 'One input. Infinite output.',
      desc: 'Transform a single idea, article, or video into a full multi-platform content library. Posts, threads, newsletters, scripts — generated, optimised for each platform, and ready to publish.',
      color: '#ff9a00',
      paper: '#fff3e0',
      status: 'live',
      whoItsFor: 'Creators and indie hackers who want to multiply their reach across social channels without spending hours writing.',
      icon: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18M9 21V9"/></svg>`,
      features: [
        { title: 'One-Click Expansion', desc: 'Drop in a URL, paste text, or upload a doc. Content Factory builds a full content calendar around it instantly.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="16 3 21 3 21 8"/><line x1="4" y1="20" x2="21" y2="3"/><polyline points="21 16 21 21 16 21"/><line x1="15" y1="15" x2="21" y2="21"/></svg>` },
        { title: 'Platform Optimiser', desc: 'Each piece is rewritten for the specific platform — Twitter threads, LinkedIn posts, newsletters, TikTok scripts — each optimised for native engagement.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="3" width="20" height="14" rx="2"/><line x1="8" y1="21" x2="16" y2="21"/><line x1="12" y1="17" x2="12" y2="21"/></svg>` },
        { title: 'Brand Voice Lock', desc: 'Upload 3 examples of your best content and Content Factory learns your tone, style, and vocabulary. Every output sounds like you.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 20h9"/><path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"/></svg>` },
        { title: 'Repurposing Engine', desc: 'Turn old content into new. Point it at last year\'s blog posts and get a fresh batch of social content without writing a word.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="1 4 1 10 7 10"/><path d="M3.51 15a9 9 0 1 0 .49-3.8"/></svg>` },
        { title: 'Schedule & Publish', desc: 'Connect your social accounts and schedule directly from Content Factory. One workflow from idea to published.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="4" width="18" height="18" rx="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></svg>` },
        { title: 'Analytics Loop', desc: 'Track which content performs best and feed that back into future generation — the engine gets smarter the more you use it.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></svg>` },
      ],
      steps: [
        { label: 'Input your source', title: 'Drop anything in', desc: 'A URL, a PDF, raw text, a YouTube link, or a voice memo. Content Factory reads and understands it.' },
        { label: 'Choose your platforms', title: 'Pick your channels', desc: 'Select which platforms you want content for. Mix and match: Twitter, LinkedIn, newsletter, blog, YouTube description.' },
        { label: 'Review + edit', title: 'Refine in seconds', desc: 'Every output is editable inline. Tweak the tone, change a sentence, swap the hook — then approve.' },
        { label: 'Publish or schedule', title: 'Ship immediately', desc: 'Post directly or schedule to your connected accounts. Your entire content calendar can be set for the week in under 15 minutes.' },
      ],
      pricing: [
        { tier: 'Starter', price: '$19', priceSub: '/mo', note: 'Billed monthly', badge: null, featured: false, features: ['30 content pieces/month', '5 platform types', 'Brand voice training (1 profile)', 'Basic scheduling'] },
        { tier: 'Growth', price: '$49', priceSub: '/mo', note: 'Billed monthly', badge: 'Best Value', featured: true, features: ['Unlimited content pieces', 'All platform types', '3 brand voice profiles', 'Repurposing engine', 'Direct scheduling + publishing', 'Analytics dashboard'] },
        { tier: 'Agency', price: '$129', priceSub: '/mo', note: 'Billed monthly', badge: null, featured: false, features: ['Everything in Growth', '10 brand voice profiles', 'Team collaboration', 'White-label exports', 'API access', 'Priority support'] },
      ],
    },
    {
      id: 'soloscribe',
      shortName: 'Scribe',
      num: '04',
      name: 'Solo',
      nameAccent: 'Scribe',
      tagline: 'Write like a team. Publish like a founder.',
      desc: 'An AI writing assistant built for long-form creation. Proposals, blog posts, newsletters, and documentation — SoloScribe matches your voice, maintains consistency, and never loses context between sessions.',
      color: '#c87af9',
      paper: '#f3e5f5',
      status: 'live',
      whoItsFor: 'Freelancers and founders writing long-form proposals, SEO blog posts, and documentation in their unique brand voice.',
      icon: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 20h9"/><path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"/></svg>`,
      features: [
        { title: 'Voice Matching', desc: 'Upload writing samples and SoloScribe learns exactly how you write — your rhythm, vocabulary, and personality carry through every output.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 1a3 3 0 0 0-3 3v8a3 3 0 0 0 6 0V4a3 3 0 0 0-3-3z"/><path d="M19 10v2a7 7 0 0 1-14 0v-2"/><line x1="12" y1="19" x2="12" y2="23"/><line x1="8" y1="23" x2="16" y2="23"/></svg>` },
        { title: 'Long-Form AI', desc: 'Write blog posts, white papers, and guides that need depth and structure — not just bullet points. SoloScribe holds the whole document in context.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><polyline points="10 9 9 9 8 9"/></svg>` },
        { title: 'Template Library', desc: '50+ templates for every document type a solo founder needs: proposals, SOPs, case studies, pitch decks, and more.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/></svg>` },
        { title: 'Persistent Context', desc: 'SoloScribe remembers everything across sessions — your business context, past documents, client names — so you never have to re-explain yourself.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>` },
        { title: 'SEO Optimiser', desc: 'Built-in keyword analysis and SEO scoring so every blog post you publish has a fighting chance to rank.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/></svg>` },
        { title: 'Export Anywhere', desc: 'Export to Google Docs, Notion, Word, or plain markdown. Your documents live wherever your workflow lives.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>` },
      ],
      steps: [
        { label: 'Set your voice', title: 'Train once', desc: 'Upload 3–5 pieces of your existing writing. SoloScribe builds a voice profile that persists across every document.' },
        { label: 'Pick a template or start fresh', title: 'Choose your format', desc: 'Select from the library or give SoloScribe a brief. It drafts a full outline before writing a single paragraph.' },
        { label: 'Write with AI', title: 'Collaborate in real time', desc: 'Accept, reject, or modify suggestions inline. Expand sections, rewrite paragraphs, or let SoloScribe take a full first pass.' },
        { label: 'Export and publish', title: 'Ship in your format', desc: 'Export wherever you need it. Formatted, proofed, and ready to go.' },
      ],
      pricing: [
        { tier: 'Solo', price: '$15', priceSub: '/mo', note: 'Billed monthly', badge: null, featured: false, features: ['30 documents/month', '1 voice profile', 'Template library', 'Basic export (Markdown, Word)'] },
        { tier: 'Studio', price: '$39', priceSub: '/mo', note: 'Billed monthly', badge: 'Most Popular', featured: true, features: ['Unlimited documents', '3 voice profiles', 'Full template library', 'SEO optimiser', 'Persistent context memory', 'All export formats'] },
        { tier: 'Agency', price: '$99', priceSub: '/mo', note: 'Billed monthly', badge: null, featured: false, features: ['Everything in Studio', '10 voice profiles', 'Team workspace', 'Client document portals', 'API access', 'Priority support'] },
      ],
    },
    {
      id: 'solodesign',
      shortName: 'Design',
      num: '05',
      name: 'Solo',
      nameAccent: 'Design',
      tagline: 'Ship beautiful. No designer needed.',
      desc: 'Describe what you need and SoloDesign delivers polished, brand-consistent visual assets. Brand kits, social graphics, pitch decks, and more — generated at the quality level of a professional designer, in minutes.',
      color: '#ffe800',
      paper: '#fffde7',
      status: 'live',
      whoItsFor: 'Product builders who need high-quality pitch decks, social cards, and branding kits without hiring a design agency.',
      icon: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="10"/><path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"/><path d="M2 12h20"/></svg>`,
      features: [
        { title: 'Brand Kit Generator', desc: 'Upload your logo and SoloDesign extracts a full brand kit — colours, fonts, spacing rules — that every asset respects automatically.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="3"/><path d="M19.07 4.93A10 10 0 0 0 5 5a10 10 0 0 0 0 14 10 10 0 0 0 14.07-1"/></svg>` },
        { title: 'Social Asset Engine', desc: 'Generate on-brand graphics for every platform — Instagram, LinkedIn, Twitter, YouTube — sized and formatted correctly, every time.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><polyline points="21 15 16 10 5 21"/></svg>` },
        { title: 'Pitch Deck Builder', desc: 'Turn a bullet-point outline into a designed, investor-ready pitch deck with consistent visual hierarchy and your brand throughout.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="3" width="20" height="14" rx="2"/><line x1="8" y1="21" x2="16" y2="21"/><line x1="12" y1="17" x2="12" y2="21"/></svg>` },
        { title: 'Template Library', desc: '500+ templates across social, sales, launches, and presentations — ready to customise and export instantly.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/></svg>` },
        { title: 'One-Click Resize', desc: 'Design once, export to every format you need. LinkedIn carousel, Instagram story, YouTube thumbnail — one click.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="15 3 21 3 21 9"/><polyline points="9 21 3 21 3 15"/><line x1="21" y1="3" x2="14" y2="10"/><line x1="3" y1="21" x2="10" y2="14"/></svg>` },
        { title: 'Export + Handoff', desc: 'Download source files, PNGs, or presentation decks. Your assets are ready for immediate use or further editing.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>` },
      ],
      steps: [
        { label: 'Upload your brand', title: 'Set the visual system', desc: 'Start with a logo, website URL, or a short brand description. SoloDesign extracts the visual language automatically.' },
        { label: 'Describe what you need', title: 'Prompt the asset', desc: 'Ask for a pitch deck, launch graphic, social ad, or full campaign. You describe the intention; SoloDesign handles the execution.' },
        { label: 'Review variations', title: 'Pick your favourite', desc: 'Get multiple polished concepts, compare them side by side, and tweak the winning direction in seconds.' },
        { label: 'Export and ship', title: 'Use it immediately', desc: 'Download in all required sizes and formats. Your visuals are ready to post, present, or publish.' },
      ],
      pricing: [
        { tier: 'Starter', price: '$19', priceSub: '/mo', note: 'Billed monthly', badge: null, featured: false, features: ['50 exports/month', 'Brand kit generator', 'Social asset engine', 'Basic templates'] },
        { tier: 'Pro', price: '$49', priceSub: '/mo', note: 'Billed monthly', badge: 'Most Popular', featured: true, features: ['Unlimited exports', '500+ templates', 'Pitch deck builder', 'One-click resize', 'Premium brand controls'] },
        { tier: 'Studio', price: '$119', priceSub: '/mo', note: 'Billed monthly', badge: null, featured: false, features: ['Everything in Pro', '10 brand workspaces', 'Team collaboration', 'Priority rendering', 'White-label exports'] },
      ],
    },
    {
      id: 'soloscout',
      shortName: 'Scout',
      num: '06',
      name: 'Solo',
      nameAccent: 'Scout',
      tagline: 'Find opportunities first.',
      desc: 'AI market intelligence for solo founders. SoloScout monitors trends, surfaces leads, tracks competitors, and alerts you to opportunities before everyone else jumps in.',
      color: '#00e676',
      paper: '#e8f5e9',
      status: 'soon',
      whoItsFor: 'Indie hackers looking to identify warm sales leads, emerging market niches, and track competitor updates before others.',
      icon: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/></svg>`,
      features: [
        { title: 'Trend Radar', desc: 'Monitor keywords, niches, and emerging conversations across the web to see where demand is building before it peaks.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/></svg>` },
        { title: 'Lead Discovery', desc: 'Find warm prospects already asking for the kind of solution you provide — no cold fishing required.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 3v18h18"/><path d="M18 9l-5 5-3-3-5 5"/></svg>` },
        { title: 'Competitor Tracking', desc: 'Watch what similar products are shipping, pricing, and promoting so you can respond strategically instead of reactively.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M2 12h20"/><path d="M12 2v20"/><circle cx="12" cy="12" r="9"/></svg>` },
        { title: 'Opportunity Scoring', desc: 'SoloScout scores leads and market signals by urgency, fit, and likely value so you know where to focus first.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></svg>` },
        { title: 'Alerting', desc: 'Get real-time alerts when a keyword spikes, a lead appears, or a competitor ships something worth paying attention to.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg>` },
        { title: 'Weekly Briefings', desc: 'A concise, founder-friendly summary of what changed this week, what matters, and what action you should take next.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg>` },
      ],
      steps: [
        { label: 'Define your market', title: 'Set your watchlist', desc: 'Enter the topics, keywords, competitors, and target customer signals you care about. SoloScout starts tracking immediately.' },
        { label: 'Collect signals', title: 'AI does the scanning', desc: 'The system monitors the web for relevant movement — conversations, demand spikes, product launches, and prospect intent.' },
        { label: 'Score the opportunities', title: 'See what matters most', desc: 'Signals are ranked for fit and urgency so you can act on the best opportunities first.' },
        { label: 'Take action', title: 'Turn insight into growth', desc: 'Reach out, build, position, or pivot faster than competitors who are flying blind.' },
      ],
      pricing: null,
      waitlistTitle: 'Get the signal before the crowd.',
      waitlistDesc: 'SoloScout is currently in development. Join the waitlist to be first in line when market intelligence for solo founders goes live.',
    },
    {
      id: 'soloconnect',
      shortName: 'Connect',
      num: '07',
      name: 'Solo',
      nameAccent: 'Connect',
      tagline: 'Your network, amplified.',
      desc: 'A smart networking and community platform for solo founders and indie hackers. SoloConnect helps you find aligned people, build accountability circles, and create meaningful professional momentum without wasting time.',
      color: '#ff4ec8',
      paper: '#fce4ec',
      status: 'soon',
      whoItsFor: 'Independent entrepreneurs seeking high-quality networking, accountability check-ins, and peer skill swaps.',
      icon: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M17 20h5v-2a3 3 0 0 0-5.356-1.857"/><path d="M9 20H4v-2a3 3 0 0 1 5.356-1.857"/><circle cx="12" cy="10" r="3"/><path d="M6 20v-2a4 4 0 0 1 4-4h4a4 4 0 0 1 4 4v2"/></svg>`,
      features: [
        { title: 'Smart Matching', desc: 'AI pairs you with founders, freelancers, and collaborators who match your stage, goals, skillset, and energy.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M16 3h5v5"/><path d="M8 21H3v-5"/><path d="M21 3l-7 7"/><path d="M3 21l7-7"/></svg>` },
        { title: 'Accountability Pods', desc: 'Join small founder groups for weekly check-ins, honest feedback, and momentum support — without the noise of massive communities.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="9" cy="7" r="4"/><path d="M17 11v-1a4 4 0 0 0-4-4"/><path d="M5 21v-2a4 4 0 0 1 4-4h6a4 4 0 0 1 4 4v2"/></svg>` },
        { title: 'AI Intro Messages', desc: 'No awkward networking openers. SoloConnect drafts warm introduction messages based on mutual context and shared goals.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>` },
        { title: 'Founder Rooms', desc: 'Drop into topic-based rooms for fundraising, growth, product, AI tooling, or mindset. Find your people faster.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="4" width="18" height="14" rx="2"/><path d="M8 20h8"/><path d="M12 18v2"/></svg>` },
        { title: 'Skill Exchange', desc: 'Trade skills directly inside the network — design for copy, strategy for engineering, feedback for accountability.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M8 7h12"/><path d="M8 12h12"/><path d="M8 17h12"/><path d="M3 7h.01"/><path d="M3 12h.01"/><path d="M3 17h.01"/></svg>` },
        { title: 'Relationship CRM', desc: 'Keep track of who you\'ve met, what you discussed, and what to follow up on so your network compounds over time.', icon: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="3" width="20" height="18" rx="2"/><path d="M8 7h8"/><path d="M8 11h8"/><path d="M8 15h5"/></svg>` },
      ],
      steps: [
        { label: 'Build your profile', title: 'Tell your story', desc: 'Share where you are in your journey, what you\'re building, and what kinds of connections you\'re looking for.' },
        { label: 'Get matched', title: 'Let AI find your people', desc: 'SoloConnect surfaces 5 new high-quality matches every week based on your profile, goals, and activity.' },
        { label: 'Connect with intent', title: 'No cold outreach awkwardness', desc: 'AI-written introduction messages make reaching out feel natural. Hit send in one click.' },
        { label: 'Build relationships', title: 'Grow your inner circle', desc: 'Join accountability pods, participate in founder rooms, and trade skills. The community does what a team used to do.' },
      ],
      pricing: null,
      waitlistTitle: 'Join the founding community.',
      waitlistDesc: 'SoloConnect launches with a founding cohort of 500 members. Join the waitlist now to secure your spot — founding members get lifetime access at pre-launch pricing.',
    },
  ]
};
